-- Drop foreign key constraints
-- ALTER TABLE comment DROP FOREIGN KEY IF EXISTS FKqrw88se6l55i5kaik5wey0j36;
-- ALTER TABLE comment DROP FOREIGN KEY IF EXISTS FKfpulud7pck6q6kxtbuiv3yepn;
-- ALTER TABLE comment_like DROP FOREIGN KEY IF EXISTS FKqlv8phl1ibeh0efv4dbn3720p;
-- ALTER TABLE comment_like DROP FOREIGN KEY IF EXISTS FKju1xue6tbcs0fi4flcig66xuc;
-- ALTER TABLE dream_category DROP FOREIGN KEY IF EXISTS FKacij26idcwirsonuj5cjxbmk5;
-- ALTER TABLE dream_category DROP FOREIGN KEY IF EXISTS FK4u6g29vfd9mie35lwpqamktjp;
-- ALTER TABLE dream_like DROP FOREIGN KEY IF EXISTS FKjy1l27u1ta1kpkv2yvog4yy5h;
-- ALTER TABLE dream_like DROP FOREIGN KEY IF EXISTS FK6m3k7xoinayo2dqrgnfl4dmwr;

-- Drop tables
-- DROP TABLE IF EXISTS comment;
-- DROP TABLE IF EXISTS comment_like;
-- DROP TABLE IF EXISTS dream_category;
-- DROP TABLE IF EXISTS dream_like;
-- DROP TABLE IF EXISTS dream;
-- DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS category;

-- -- Create tables
-- CREATE TABLE category (
--                           category_id INT AUTO_INCREMENT PRIMARY KEY,
--                           word VARCHAR(255),
--                           type ENUM('character', 'dreamType', 'location', 'mood', 'objects')
-- ) ENGINE=InnoDB;
--
-- CREATE TABLE users (
--                        id INT AUTO_INCREMENT PRIMARY KEY,
--                        createdDate DATETIME(6),
--                        lastModifiedDate DATETIME(6),
--                        email VARCHAR(255),
--                        name VARCHAR(255),
--                        nickname VARCHAR(255),
--                        providerUserId VARCHAR(255),
--                        refreshToken VARCHAR(255),
--                        role VARCHAR(255)
-- ) ENGINE=InnoDB;
--
-- CREATE TABLE dream (
--                        dream_id INT AUTO_INCREMENT PRIMARY KEY,
--                        is_shared BOOLEAN DEFAULT false,
--                        likes_count INT,
--                        user_id INT,
--                        createdDate DATETIME(6),
--                        lastModifiedDate DATETIME(6),
--                        image VARCHAR(255),
--                        interpretation VARCHAR(255),
--                        summary VARCHAR(255) NOT NULL,
--                        write_time VARCHAR(255) NOT NULL,
--                        content TINYTEXT NOT NULL,
--                        CONSTRAINT FK_dream_user FOREIGN KEY (user_id) REFERENCES users(id)
-- ) ENGINE=InnoDB;
--
-- CREATE TABLE comment (
--                          comment_id INT AUTO_INCREMENT PRIMARY KEY,
--                          dream_id INT,
--                          likes_count INT,
--                          user_id INT,
--                          content VARCHAR(255),
--                          CONSTRAINT FK_comment_dream FOREIGN KEY (dream_id) REFERENCES dream(dream_id),
--                          CONSTRAINT FK_comment_user FOREIGN KEY (user_id) REFERENCES users(id)
-- ) ENGINE=InnoDB;
--
-- CREATE TABLE comment_like (
--                               comment_like_id INT AUTO_INCREMENT PRIMARY KEY,
--                               comment_id INT,
--                               user_id INT,
--                               CONSTRAINT FK_comment_like_comment FOREIGN KEY (comment_id) REFERENCES comment(comment_id),
--                               CONSTRAINT FK_comment_like_user FOREIGN KEY (user_id) REFERENCES users(id)
-- ) ENGINE=InnoDB;
--
-- CREATE TABLE dream_category (
--                                 dream_category_id INT AUTO_INCREMENT PRIMARY KEY,
--                                 category_id INT,
--                                 dream_id INT,
--                                 CONSTRAINT FK_dream_category_category FOREIGN KEY (category_id) REFERENCES category(category_id),
--                                 CONSTRAINT FK_dream_category_dream FOREIGN KEY (dream_id) REFERENCES dream(dream_id)
-- ) ENGINE=InnoDB;
--
-- CREATE TABLE dream_like (
--                             dream_like_id INT AUTO_INCREMENT PRIMARY KEY,
--                             dream_id INT,
--                             user_id INT,
--                             CONSTRAINT FK_dream_like_dream FOREIGN KEY (dream_id) REFERENCES dream(dream_id),
--                             CONSTRAINT FK_dream_like_user FOREIGN KEY (user_id) REFERENCES users(id)
-- ) ENGINE=InnoDB;
