export const mainDummy = {
  username: '민채',
  totalCount: 5,
  dreams: [
    {
      dreamId: 1,
      content: '고구마 무스에 소금을 뿌려서...',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240701',
    },
    {
      dreamId: 2,
      content: '하루종일 산책만 해서...',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240702',
    },
    {
      dreamId: 3,
      content: '더미 꿈 내용 3',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240703',
    },
    {
      dreamId: 4,
      content: '더미 꿈 내용 4',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240704',
    },
    {
      dreamId: 5,
      content: '더미 꿈 내용 5',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240705',
    },
    {
      dreamId: 6,
      content: '더미 꿈 내용 6',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240706',
    },
    {
      dreamId: 7,
      content: '더미 꿈 내용 7',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240707',
    },
    {
      dreamId: 8,
      content: '더미 꿈 내용 8',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240708',
    },
    {
      dreamId: 9,
      content: '더미 꿈 내용 9',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240709',
    },
    {
      dreamId: 10,
      content: '더미 꿈 내용 10',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240710',
    },
    {
      dreamId: 11,
      content: '더미 꿈 내용 11',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240711',
    },
    {
      dreamId: 12,
      content: '더미 꿈 내용 12',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240712',
    },
    {
      dreamId: 13,
      content: '더미 꿈 내용 13',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240713',
    },
    {
      dreamId: 14,
      content: '더미 꿈 내용 14',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240714',
    },
    {
      dreamId: 15,
      content: '더미 꿈 내용 15',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240715',
    },
    {
      dreamId: 16,
      content: '더미 꿈 내용 16',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240716',
    },
    {
      dreamId: 17,
      content: '더미 꿈 내용 17',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240717',
    },
    {
      dreamId: 18,
      content: '더미 꿈 내용 18',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240718',
    },
    {
      dreamId: 19,
      content: '더미 꿈 내용 19',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240719',
    },
    {
      dreamId: 20,
      content: '더미 꿈 내용 20',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240720',
    },
    {
      dreamId: 21,
      content: '더미 꿈 내용 21',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240721',
    },
    {
      dreamId: 22,
      content: '더미 꿈 내용 22',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240722',
    },
    {
      dreamId: 23,
      content: '더미 꿈 내용 23',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240723',
    },
    {
      dreamId: 24,
      content: '더미 꿈 내용 24',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240724',
    },
    {
      dreamId: 25,
      content: '더미 꿈 내용 25',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240725',
    },
    {
      dreamId: 26,
      content: '더미 꿈 내용 26',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240726',
    },
    {
      dreamId: 27,
      content: '더미 꿈 내용 27',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240727',
    },
    {
      dreamId: 28,
      content: '더미 꿈 내용 28',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240728',
    },
    {
      dreamId: 29,
      content: '더미 꿈 내용 29',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240729',
    },
    {
      dreamId: 30,
      content: '더미 꿈 내용 30',
      image: '/src/assets/MainpageTest.jpg',
      writeDate: '20240730',
    },
  ],
};
